name: word-puzzle-solver-api
services:
  - name: api
    type: web
    build:
      type: buildpack
      buildpack: python
    run_command: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 main:app
    ports:
      - port: 8000
        protocol: http
    env:
      - PORT=8000
      - SESSION_SECRET=koyeb-secure-session-key
    instance_type: nano
    autoscaling:
      min: 1
      max: 2
    health_check:
      http:
        path: /health
        port: 8000
      initial_delay_seconds: 60
      timeout_seconds: 15
      period_seconds: 30
      success_threshold: 1
      failure_threshold: 3